
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    ca_org7:
        networks:
            skcript:
                aliases:
                    - ca_org7
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 
        image: hyperledger/fabric-ca:latest
        hostname: ca.org7.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org7
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org7.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/361c253239c112877875ba1aaec61b92f34e4311d285d9f4ab0b07d817f4aea2_sk
        ports:
            - 14054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org7.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org7:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb0_org7
        networks:
           - skcript

    couchdb1_org7:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb1_org7
        networks:
           - skcript
