
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    ca_org5:
        networks:
            skcript:
                aliases:
                    - ca_org5
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 
        image: hyperledger/fabric-ca:latest
        hostname: ca.org5.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org5
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org5.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ae977ecdda62fb08bc97c049c84aa16b72f4de0d055468099edf70ff06cc61a1_sk
        ports:
            - 12054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org5.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org5:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb0_org5
        networks:
           - skcript

    couchdb1_org5:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb1_org5
        networks:
           - skcript
